### ISSUE TITLE
Change the line weigth func?

### ISSUE THREAD

**Issue by TSaltedfishKing** [zbchristian/PPTPenTool#1]
Dear Developer, It is a good idea that make a tool bar on present mode.
Now i meet a problem while i am present math class and try to use ppt pen to draw a anwser, but the line weigth is tool small that most of students talk to me, could you add this function?

**Comment by zbchristian** [comment]
Unfortunately there seems to be currently no way to set the line width programmatically in presenter mode. At least I did not find it.
In my case, on a Microsoft Surface, the line is not very thin and depends on the pressure. Its not perfect, but works reasonably well.
